# -*- coding: utf-8 -*-
"""Work Sample Part 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iI-XAtVW7BKzkzW6f4krDj--dsclu1XQ

**Data Sources** <br>
All data ranges are from 1/1/2015 to 12/31/2020  to encompass a full five years of data (with the exception of RACE, which went public in 10/2015). Data was recorded on a monthly basis on the first day of each month.

**Commodities** <br>
All commodity data was selected as a Producer Price Index by Commodity
* [Steel](https://fred.stlouisfed.org/series/WPU101707)
* [Rubber Tires](https://fred.stlouisfed.org/series/WPU071201)
* [Glass](https://fred.stlouisfed.org/series/WPU13110511)
* [Aluminum](https://fred.stlouisfed.org/series/PCU3313153313150)

**Stocks**
* [Tesla (TSLA)](https://finance.yahoo.com/quote/TSLA/history?period1=1420070400&period2=1609372800&interval=1mo&filter=history&frequency=1mo&includeAdjustedClose=true)
* [General Motors (GM)](https://finance.yahoo.com/quote/GM/history?period1=1420070400&period2=1609372800&interval=1mo&filter=history&frequency=1mo&includeAdjustedClose=true)
* [Ford (F)](https://finance.yahoo.com/quote/F/history?period1=1420070400&period2=1609372800&interval=1mo&filter=history&frequency=1mo&includeAdjustedClose=true)
* [Honda (HMC)](https://finance.yahoo.com/quote/HMC/history?period1=1420070400&period2=1609372800&interval=1mo&filter=history&frequency=1mo&includeAdjustedClose=true)
* [Ferrari (RACE)](https://finance.yahoo.com/quote/RACE/history?period1=1447200000&period2=1609372800&interval=1mo&filter=history&frequency=1mo&includeAdjustedClose=true)

**Indexes**
* [Global Auto Index (CARZ)](https://finance.yahoo.com/quote/CARZ/history?period1=1420070400&period2=1609372800&interval=1mo&filter=history&frequency=1mo&includeAdjustedClose=true)
"""

import pandas as pd
import numpy as np
import plotly
import plotly.express as px

import warnings
warnings.filterwarnings('ignore')

"""# Importing Data

Import data on commodity prices
"""

steel = pd.read_csv("https://raw.githubusercontent.com/cawarburton5/ForgeNode/main/SteelCommodityData.csv")
rubber = pd.read_csv("https://raw.githubusercontent.com/cawarburton5/ForgeNode/main/TiresCommodityData.csv")
glass = pd.read_csv("https://raw.githubusercontent.com/cawarburton5/ForgeNode/main/GlassCommodityData.csv")
aluminum = pd.read_csv("https://raw.githubusercontent.com/cawarburton5/ForgeNode/main/AluminumCommodityData.csv")

"""Import data on stock prices"""

tesla = pd.read_csv("https://raw.githubusercontent.com/cawarburton5/ForgeNode/main/TSLA.csv")
gm = pd.read_csv("https://raw.githubusercontent.com/cawarburton5/ForgeNode/main/GM.csv")
ford = pd.read_csv("https://raw.githubusercontent.com/cawarburton5/ForgeNode/main/F.csv")
carz = pd.read_csv("https://raw.githubusercontent.com/cawarburton5/ForgeNode/main/CARZ.csv")
honda = pd.read_csv("https://raw.githubusercontent.com/cawarburton5/ForgeNode/main/HMC.csv")
ferrari = pd.read_csv("https://raw.githubusercontent.com/cawarburton5/ForgeNode/main/RACE.csv")

"""# Data Clenaning

Create indicator columns
"""

# Stocks
tesla['id'] = 'Tesla (TSLA)'
gm['id'] = 'GM'
ford['id'] = 'Ford (F)'
honda['id'] = 'Honda (HMC)'
ferrari['id'] = 'Ferrari (RACE)'

# Index
carz['id'] = 'Global Auto Index (CARZ)'

# Commodities
steel['id'] = 'Steel'
rubber['id'] = 'Rubber'
glass['id'] = 'Glass'
aluminum['id'] = 'Aluminum'

# Stocks
tesla['type'] = 'Stock'
gm['type'] = 'Stock'
ford['type'] = 'Stock'
honda['type'] = 'Stock'
ferrari['type'] = 'Stock'

# Index
carz['type'] = 'Index'

# Commodities
steel['type'] = 'Commodity'
rubber['type'] = 'Commodity'
glass['type'] = 'Commodity'
aluminum['type'] = 'Commodity'

"""Rename columns"""

steel.rename(columns={'DATE':'date', 'WPU101707':'price'}, inplace=True)
rubber.rename(columns={'DATE':'date', 'WPU071201':'price'}, inplace=True)
glass.rename(columns={'DATE':'date', 'WPU13110511':'price'}, inplace=True)
aluminum.rename(columns={'DATE':'date', 'PCU3313153313150':'price'}, inplace=True)

"""# Joining Data

Concatenate stock and commodities dataframes
"""

# Combine stock dataframes
stocks = pd.concat([tesla, gm, ford, carz, honda, ferrari])

# Combine commodities dataframes
commodities = pd.concat([steel, rubber, glass, aluminum])


# Create a stocks dataframe that matches commodities
stocks_for_concat = stocks[['Date', 'Close', 'id','type']]
stocks_for_concat.rename(columns={'Date':'date', 'Close':'price', 'ID':'id','Type':'type'}, inplace=True)

# Concatenate stock and commodities data
prices = pd.concat([stocks_for_concat, commodities])

# Adjust date to a datetime format
prices['date'] = pd.to_datetime(prices['date'])

prices.head(10)

"""# Plotting the Data

Creating a Line Chart
"""

fig1 = px.line(prices, x='date', y='price', color='id',
        labels = {'price':'Price ($)','date':'Date', 'id':'Commodity or Stock'},
        title = '<b>Price of Commodities and Stocks Over Time</b>'
        )

# Adjusting Graph Aesthetics
fig1.update_layout(legend=dict(
    yanchor="top",
    y=0.98,
    xanchor="left",
    x=0.01),
    font_family="Arial",
    font_color="black",
    title_font_family="Arial",
    title_font_color="maroon",
    title_font_size = 20,
    title={
        'y':0.9,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top'}
      )

fig1.update_traces(mode="lines", hovertemplate = 'Date: %{x} <br> Price: %{y:$.2f}')

fig2 = px.line(prices, x='date', y='price', color='id', facet_row= 'type',
        labels = {'price':'Price ($)','date':'Date', 'id':'ID','type':'Type'},
        title = '<b>Price of Commodities and Stocks Over Time</b>'
        )


# Adjusting Graph Aesthetics
fig2.update_layout(
    font_family="Arial",
    font_color="black",
    title_font_family="Arial",
    title_font_color="maroon",
    title_font_size = 20,
    title={
        'y':0.9,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top'},
    yaxis_range=[0,260] 
      )
fig2

"""Plot Percent Change of Commodity and Stock Prices in 2020"""

prices['pctchange'] = prices['price'].astype(float).pct_change()

prices2020 = prices[prices['date'].dt.year == 2020]

fig3 = px.line(prices2020, x='date', y='pctchange', color='id', facet_row = 'type',
        labels = {'pctchange':'Percent Change','date':'Date','id':'ID','type':'Type'},
        title = '<b>Percent Change of Prices of Commodities and Stocks in 2020</b>',
        height=900, error_y=None
        )

fig3.update_layout(
    font_family="Arial",
    font_color="black",
    title_font_family="Arial",
    title_font_color="maroon",
    title_font_size = 20,
    title={
        'y':.95,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top'}
      )

#fig3.update_yaxes(range=[-0.5, 0.5], row=3, col=1)

fig3